apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: notification-dev
type: Opaque
stringData:
  TIME_ZONE: Asia/Singapore
  POSTGRES_HOST: "10.250.64.3"
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: notification
  ENV_MODE: dev
  NATS_HOST: "my-nats.default.svc.cluster.local"
  NATS_PORT: "4222"